quarkus:
  http:
    port: 8080
    root-path: /api
  rest-client:
    you-bike-api:
      url: "https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json"
      scope: javax.inject.Singleton
      connect-timeout: 5000
      read-timeout: 10000
